const plantData = [
    {   // Completed
        "genus": "Agapanthus",
        "species": "Campanulatus",
        "name": "Bell Agapanthus",
        "nickname": "Lily of the Nile",
        "family": "Liliaceae",
        "category": "tropicals and tender perennial",
        "height": "24-40 inches (0.6-1 m)",
        "sun exposure": "full sun",
        "soil": "ordinary, well drained",
        "water requirement": ["average water needs, water regularly, do not overwater"],
        "foliage": ["Deciduous","This plant is resistant to deer"],
        "bloom time": ["06","09"],   // starting month - end month
        "bloom characteristics": ["This plant is attractive to bees, butterflies and/or birds",
            "Flowers are fragrant"],
        "planting": ["For regions with rather cool winters, plant your lily of the Nile in spring, for them to harden before the first winter.",
            "Elsewhere, for mild-wintered climates, lily of the Nile can be planted in fall.",
            "If you have purchased your Agapanthus in pots, you can plant them all year round, except during frost and heat spells."],
        "plant hardiness zones": ["7b", "10b"],
        "propagation methods": ["By dividing the rootball from seed",
            "Sow indoors before last frost"],
        "seed collecting": ["Bag seedheads to capture ripening seed"],
        "danger": "Parts of plant are poisonous if ingested",
    },
    {   // Completed
        "genus": "Helianthus",
        "species": "Salicifolius",
        "name": "Swamp Sunflower",
        "nickname": "First Light",
        "family": "Asteraceae",
        "category": "annual",
        "height": "6-13 feet (2-4 meters)",
        "sun exposure": "full sun",
        "soil": "rich enough",
        "water requirement": ["average water needs, water regularly, do not overwater",
            "requires consistently moist soil", "do not let dry out between waterings"],
        "foliage": ["Herbaceous","Succulent","This plant is resistant to deer"],
        "bloom time": ["07","10"],   // starting month - end month
        "bloom characteristics": ["This plant is attractive to bees, butterflies and/or birds"],
        "planting": ["If you’ve purchased your sunflower plants already formed as young seedlings, transplant them from their nursery pot to the ground from April to June.",
            "Water often at the start, especially in case of elevated temperatures."],
        "plant hardiness zones": ["5a", "9b"],
    },
    {   // Completed
        "genus":"Helleborus",
        "species": "x Glandorfensis",
        "name": "Winter Rose",
        "nickname": "Ice n' Rose",
        "family": "Ranunculaceae",
        "category": "perennial herbaceous flower",
        "height": "12-30 inches (30-80 cm)",
        "sun exposure": "shade to part shade",
        "soil": "rich, cool, well-draining",
        "water requirement": ["average water needs, water regularly, do not overwater"],
        "foliage": ["Evergreen"],
        "bloom time": ["02","04"],   // starting month - end month
        "bloom characteristics": ["This plant is attractive to bees, butterflies and/or birds"],
        "planting": ["spring, end of summer"],
        "plant hardiness zones": ["5a", "8b"],
    },
    {   // Completed
        "genus":"Salvia",
        "species": "Farinacea",
        "name": "Mealycup Sage",
        "nickname": "Victoria Blue",
        "family": "Lamiaceae",
        "category": "perennial",
        "height": "12-18 inches (30-45 cm)",
        "sun exposure": "sun to partial shade",
        "soil": "ordinary",
        "soil pH requirements": ["6.1 to 6.5 (mildly acidic)",
            "6.6 to 7.5 (neutral)",
            "7.6 to 7.8 (mildly alkaline)"],
        "water requirement": ["average water needs, water regularly, do not overwater",
            "Drought-tolerant",
            "suitable for xeriscaping"],
        "where to grow": "Grow outdoors year-round in hardiness zone",
        "foliage": ["Herbaceous","This plant is resistant to deer"],
        "bloom time": ["04","07"],   // starting month - end month
        "bloom characteristics": ["This plant is attractive to bees, butterflies and/or birds"],
        "planting": ["With its upright habit of growth, it is best suited for use as a 'thriller' in the 'spiller-thriller-filler' container combination.",
            "Plant it near the center of the pot, surrounded by smaller plants and those that spill over the edges."],
        "plant hardiness zones": ["7b", "11a"],
        "propagation methods": ["From softwood cuttings",
            "From seed; direct sow outdoors in fal",
            "From seed; direct sow after last frost"],
        "seed collecting": ["Bag seedheads to capture ripening seed",
            "Properly cleaned, seed can be successfully stored"],
    },
    {   // Completed
        "genus":"Chrysanthemum",
        "species": "x Grandiflorum",
        "name": "Garden Mum",
        "nickname": "Harmony",
        "family": "Asteraceae",
        "category": "perennial",
        "height": "18-24 inches (45-60 cm)",
        "sun exposure": "full sun",
        "soil": "ordinary",
        "soil pH requirements": ["6.1 to 6.5 (mildly acidic)",
            "6.6 to 7.5 (neutral)",
            "7.6 to 7.8 (mildly alkaline)"],
        "water requirement": ["average water needs, water regularly, do not overwater"],
        "where to grow": "Can be grown as an annual",
        "foliage": ["Herbaceous"],
        "bloom time": ["07","10"],   // starting month - end month
        "planting": ["Chrysanthemum is planted ideally in spring. Indeed, blooms at the end of summer or during fall, it will have developed a great root system and will resist the harshness of fall and winter much better.",
            "Plant Chrysanthemum purchased in pots in fall directly to the ground. Also possible are larger pots and garden boxes, preferably with soil mix, but hardiness won’t be as good."],
        "plant hardiness zones": ["5a", "9b"],
        "seed collecting": ["plant does not set seed, flowers are sterile, or plants will not come true from seed"],
    },
];

export { plantData };