import { StyleSheet } from 'react-native';
import { theme1, theme2, theme3, fontFamilies } from './../../../../App.ThemeStyle.js';

export default StyleSheet.create({
    weatherNowContainer: {
        flex: 10,
        backgroundColor:'#679C73',
    },
    // background image style from
    // https://medium.com/@mateus17v/a-simple-animation-for-background-react-native-using-animated-498272a69fa4
    backgroundImage: {
        width: '100%',
        height: '100%',
        position: 'absolute',
        left: 0,
        flex: 1,
        opacity: .5,
    },
    row: {
        flex: 1,
        flexDirection: 'row',
        // backgroundColor: '#c0d1b8',
    },
    block: {
        flex: 1,
        justifyContent: 'center',
        margin: 10,
        marginBottom: 15,
        borderWidth: 2,
        borderRadius: 10,
        backgroundColor: 'white',
        borderColor: 'white',
        shadowColor: 'black',
        shadowOffset: {
            width: 0, 
            height: 4
        },
        shadowOpacity: 0.6,
        shadowRadius: 3.5,
        elevation: 5,
    },
    blockContent: {
        fontWeight: 'bold',
        fontFamily: fontFamilies,
        fontSize: 25,
        textAlign: 'center',
    },
    'icon-ios': {
        flex: 1,
        fontSize: 23,
        color: theme1,
        textAlign: 'left',
        paddingLeft: 5,
    },
    'icon-android': {
        flex: 1,
        fontSize: 19,
        color: theme1,
        textAlign: 'left',
        paddingLeft: 5,
    },
    'infoIcon-ios': {
        flex: 1,
        fontSize: 23,
        color: 'black',
        textAlign: 'right',
        paddingRight: 5,
    },
    'infoIcon-android': {
        flex: 1,
        fontSize: 19,
        color: 'black',
        textAlign: 'right',
        paddingRight: 5,
    },
    'number-ios': {
        fontWeight: 'bold',
        fontFamily: fontFamilies,
        fontSize: 60,
        color: 'grey',
        textAlign: 'center',
    },
    'number-android': {
        fontWeight: 'bold',
        fontFamily: fontFamilies,
        fontSize: 44,
        color: 'grey',
        textAlign: 'center',
    },
    'unit-ios': {
        fontWeight: 'bold',
        fontFamily: fontFamilies,
        fontSize: 20,
        color: 'grey',
        textAlign: 'right',
        paddingRight: 20,
    },
    'unit-android': {
        fontWeight: 'bold',
        fontFamily: fontFamilies,
        fontSize: 17,
        color: 'grey',
        textAlign: 'right',
        paddingRight: 20,
    },
    'weatherIcon-ios': {
        fontWeight: 'bold',
        fontFamily: fontFamilies,
        fontSize: 70,
        color: 'grey',
        textAlign: 'center',
    },
    'weatherIcon-android': {
        fontWeight: 'bold',
        fontFamily: fontFamilies,
        fontSize: 55,
        color: 'grey',
        textAlign: 'center',
    },
    'weatherName-ios': {
        fontWeight: 'bold',
        fontFamily: fontFamilies,
        fontSize: 18,
        color: 'grey',
        textAlign: 'center',
    },
    'weatherName-android': {
        fontWeight: 'bold',
        fontFamily: fontFamilies,
        fontSize: 15,
        color: 'grey',
        textAlign: 'center',
    },
    'windDirection-ios': {
        flex: 3,
        fontWeight: 'bold',
        fontFamily: fontFamilies,
        fontSize: 18,
        color: 'grey',
        textAlign: 'left',
        paddingLeft: 10,
    },
    'windDirection-android': {
        flex: 3,
        fontWeight: 'bold',
        fontFamily: fontFamilies,
        fontSize: 15,
        color: 'grey',
        textAlign: 'left',
        paddingLeft: 10,
    },
    'windUnit-ios': {
        flex: 1,
        fontWeight: 'bold',
        fontFamily: fontFamilies,
        fontSize: 18,
        color: 'grey',
        textAlign: 'right',
        paddingRight: 10,
    },
    'windUnit-android': {
        flex: 1,
        fontWeight: 'bold',
        fontFamily: fontFamilies,
        fontSize: 15,
        color: 'grey',
        textAlign: 'right',
        paddingRight: 10,
    },
})